### PR TITLE
Modernize Build + Fixes

### PR DESCRIPTION
**Pull request by sachaw**
Removes bundled build due to lack of use
Now has single ES2018 build (`~54kb` unminified)

### CODE REVIEW

**Comment by crossan007** [comment]
Looks fine to me.

I built this locally and used it in my app without issue.

**Comment by sachaw** [comment]
I'm going to work on a GitHub action to build a bundled andinified version and auto upload to cdnjs, as @thepoweroftwo didn't want to remove the the ability to use it the library standalone. So once that's done, I'll merge this.

**Comment by crossan007** [comment]
The way I'm pulling in this library, it's being bundled and minified into my projects final bundle

**Comment by sachaw** [comment]
Yeah, that's my reasons for the change, as the current build config is convoluted

**Pull request merged**
